services:
  backend:
    build: ./backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8000:8000'
    environment:
      - ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - '5433:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fastapi_user -d fastapi_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
